CREATE TABLE USERS_OPT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    VERSION BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE USERS_PESS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);